{% set name = "apache-airflow-providers-common-compat" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_common_compat-{{ version }}.tar.gz
  sha256: 4094ef0226e5105516797cc19aa10bf76a1486ba81cb7e1ca478ed90d6b2a1cf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.9,<4.dev0
    - apache-airflow >=2.8.0

test:
  imports:
    - airflow.providers.common.compat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-common-compat for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/common/compat/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-common-compat/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
